[package]
name = "ln_model"
version = "0.1.0"
authors = ["mweatherseed <mweatherseed@DESKTOP-82ESI4N>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.5.6"
statrs = "0.6.0"
